const ROW_PROPERTY = 1
const ROW_EXPLOSION = 2

const ROW_OBJECT = 10
const ROW_GRAPH = 11
const ROW_RELATIONSHIP = 12
const ROW_ROLE = 13

const ROW_RELATIONSHIP_TO_OBJECT = 100
const ROW_OBJECT_TO_RELATIONSHIP = 101

