FIND_PATH(GRAVM_INCLUDE_DIR NAMES gravm/runstack.h)

FIND_LIBRARY(GRAVM_LIBRARY NAMES gravm)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GRAVM DEFAULT_MSG GRAVM_LIBRARY GRAVM_INCLUDE_DIR)
IF(GRAVM_FOUND)
SET(GRAVM_LIBRARIES ${GRAVM_LIBRARY})
SET(GRAVM_INCLUDE_DIRS ${GRAVM_INCLUDE_DIR})
ELSE(GRAVM_FOUND)
SET(GRAVM_LIBRARIES)
SET(GRAVM_INCLUDE_DIRS)
ENDIF(GRAVM_FOUND)
MARK_AS_ADVANCED(GRAVM_INCLUDE_DIRS GRAVM_LIBRARIES)

