FIND_PATH(YAML_INCLUDE_DIR NAMES yaml.h)

FIND_LIBRARY(YAML_LIBRARY NAMES yaml)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(YAML DEFAULT_MSG YAML_LIBRARY YAML_INCLUDE_DIR)
IF(YAML_FOUND)
SET(YAML_LIBRARIES ${YAML_LIBRARY})
SET(YAML_INCLUDE_DIRS ${YAML_INCLUDE_DIR})
ELSE(YAML_FOUND)
SET(YAML_LIBRARIES)
SET(YAML_INCLUDE_DIRS)
ENDIF(YAML_FOUND)
MARK_AS_ADVANCED(YAML_INCLUDE_DIRS YAML_LIBRARIES)

