FIND_PATH(SQUIRREL_INCLUDE squirrel.h
	"/opt/SQUIRREL3/include"
)

FIND_LIBRARY(SQUIRREL_LIB libsquirrel.a
	"/opt/SQUIRREL3/lib"
)
FIND_LIBRARY(SQSTDLIB_LIB libsqstdlib.a
	"/opt/SQUIRREL3/lib"
)

IF(SQUIRREL_INCLUDE)
    SET(SQUIRREL_FOUND "YES")
ENDIF(SQUIRREL_INCLUDE)

